// =============================================================================
// UI Kit - Reusable components for consistent design
// =============================================================================
// This barrel file exports all kit components.
// =============================================================================

export 'animations.dart';
export 'auth_shell.dart';
export 'back_button.dart';
export 'battery_optimization_sheet.dart';
export 'brand_header.dart';
export 'brand_scaffold.dart';
export 'buttons.dart';
export 'class_details_sheet.dart';
export 'consent_dialog.dart';
export 'containers.dart';
export 'date_picker.dart';
export 'detail_row.dart';
export 'empty_hero_placeholder.dart';
export 'entity_tile.dart';
export 'error_banner.dart';
export 'form_field_tile.dart';
export 'glass_navigation_bar.dart';
export 'hero_avatar.dart';
export 'hint_bubble.dart';
export 'info_chip.dart';
export 'info_tile.dart';
export 'instructor_row.dart';
export 'layout.dart';
export 'metric_chip.dart';
export 'modals.dart';
export 'option_picker.dart';
export 'overlay_sheet.dart';
export 'page_transitions.dart';
export 'pressable_scale.dart';
export 'queued_badge.dart';
export 'quick_action_tile.dart';
export 'reminder_details_sheet.dart';
export 'root_nav_config.dart';
export 'rows.dart';
export 'screen_shell.dart';
export 'section_header.dart';
export 'sheet_header_row.dart';
export 'simple_bullet.dart';
export 'skeletons.dart';
export 'snack_bars.dart';
export 'states.dart';
export 'status_badge.dart';
export 'status_chip.dart';
export 'status_row.dart';
export 'switch.dart';
export 'theme_transition_host.dart';
export 'time_field_tile.dart';
export 'time_picker.dart';
export 'alarm_preview.dart';
export 'segmented_pills.dart';
